// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var Jest     = require("bs-jest/lib/js/src/jest.js");
var BatList  = require("bs-batteries/lib/js/src/batList.js");
var Knapsack = require("../src/Knapsack.js");

describe("Sort", (function () {
        describe("Item.sort", (function () {
                Jest.test("unequal weights", (function () {
                        var sorted = BatList.sort(Knapsack.BasicItem[/* sort */1], /* :: */[
                              /* record */[
                                /* weight */2,
                                /* value */1
                              ],
                              /* :: */[
                                /* record */[
                                  /* weight */1,
                                  /* value */6
                                ],
                                /* [] */0
                              ]
                            ]);
                        var exit = 0;
                        if (sorted) {
                          var match = sorted[1];
                          if (match) {
                            if (match[1]) {
                              exit = 1;
                            } else {
                              return Jest.Expect[/* toEqual */12](/* tuple */[
                                            6,
                                            1
                                          ])(Jest.Expect[/* expect */0](/* tuple */[
                                              sorted[0][/* value */1],
                                              match[0][/* value */1]
                                            ]));
                            }
                          } else {
                            exit = 1;
                          }
                        } else {
                          exit = 1;
                        }
                        if (exit === 1) {
                          return Jest.Expect[/* toBe */2](/* tuple */[
                                        1,
                                        1
                                      ])(Jest.Expect[/* expect */0](/* tuple */[
                                          0,
                                          0
                                        ]));
                        }
                        
                      }));
                return Jest.test("equal weights", (function () {
                              var sorted = BatList.sort(Knapsack.BasicItem[/* sort */1], /* :: */[
                                    /* record */[
                                      /* weight */1,
                                      /* value */1
                                    ],
                                    /* :: */[
                                      /* record */[
                                        /* weight */1,
                                        /* value */6
                                      ],
                                      /* [] */0
                                    ]
                                  ]);
                              var exit = 0;
                              if (sorted) {
                                var match = sorted[1];
                                if (match) {
                                  if (match[1]) {
                                    exit = 1;
                                  } else {
                                    return Jest.Expect[/* toEqual */12](/* tuple */[
                                                  1,
                                                  6
                                                ])(Jest.Expect[/* expect */0](/* tuple */[
                                                    sorted[0][/* value */1],
                                                    match[0][/* value */1]
                                                  ]));
                                  }
                                } else {
                                  exit = 1;
                                }
                              } else {
                                exit = 1;
                              }
                              if (exit === 1) {
                                return Jest.Expect[/* toBe */2](/* tuple */[
                                              1,
                                              1
                                            ])(Jest.Expect[/* expect */0](/* tuple */[
                                                0,
                                                0
                                              ]));
                              }
                              
                            }));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
