// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Curry                   = require("bs-platform/lib/js/curry.js");
var Hashtbl                 = require("bs-platform/lib/js/hashtbl.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function memoize(f) {
  var table = Hashtbl.create(/* None */0, 0);
  return (function (x) {
      try {
        return Hashtbl.find(table, x);
      }
      catch (exn){
        if (exn === Caml_builtin_exceptions.not_found) {
          var y = Curry._1(f, x);
          Hashtbl.add(table, x, y);
          return y;
        } else {
          throw exn;
        }
      }
    });
}

exports.memoize = memoize;
/* Hashtbl Not a pure module */
